### ISSUE TITLE
Incomplete support for alpha channel in the GIF format.

### ISSUE THREAD

**Issue by aryx** [rlepigre/ocaml-imagelib#42]
I'm reading a PNG or GIF (see attached files) with imagelib, and saving the image in png (I am using Cairo that can only
read png files) but the resulting png file loses the alpha property. The image background is not transparent anymore.

Here is the code I'm using to read the png or GIF:
```
let png_file_of_url url =
  let image = 
    (* ImageLib_unix.openfile url  *)
    let fn = url in
    let ich = ImageUtil_unix.chunk_reader_of_path fn in
    let extension = ImageUtil_unix.get_extension' fn in
    pr2 "reading";
    try ImageLib.openfile ~extension ich 
    with Image.Not_yet_implemented _ -> failwith (spf "PB with %s" fn)
  in
  let tmpfile = 
    (*Filename.temp_file "imagelib" ".png" 
    *) "/tmp/imagelib.png" in
  pr2 "saving";
  ImageLib_unix.writefile tmpfile image;
  tmpfile
```

**Comment by aryx** [comment]
turtle.gif:
![turtle](https://user-images.githubusercontent.com/332336/100665162-75b70780-3358-11eb-9fc0-fb1bf816211a.gif)

**Comment by aryx** [comment]
png when converted by imagemagick
![turtle-0](https://user-images.githubusercontent.com/332336/100665569-8798aa80-3358-11eb-80fe-930cd9e21cb4.png)

**Comment by aryx** [comment]
png when converted by imagelib:
![imagelib](https://user-images.githubusercontent.com/332336/100665969-997a4d80-3358-11eb-922a-6fff4bb0cac0.png)

**Comment by aryx** [comment]
If you click on the last image you'll see the wrong white background instead of a transparent background.

**Comment by aryx** [comment]
Any help or advice so i could try to fix it myself? Where should I look?

**Comment by aryx** [comment]
Any news? Is this project dead?

**Comment by aryx** [comment]
Is there a related more active project I could use instead?

**Comment by mseri** [comment]
The library has slow discussion pace, but it is not abandoned afaik, and is being reliably used in many projects.

I did try grepping for `alpha` in the sources, there are few places where this is read and interpreted, maybe that could be a start on where to look.

**Comment by aryx** [comment]
So the main author of this library is not maintaining it anymore? I have to fix the bug?

**Comment by rlepigre** [comment]
I am still around, but I am not very active any more since I am currently very busy. I cannot say that I am "maintaining" the project anymore, but there are a couple of people that seem to have interest in the project and continue maintaining it an evolving it. (I do take the time to review changes and give input whenever new features are merged, if I have time.)

Part of the problem in your case is that the `tRNS` ancillary chunk is not interpreted by the current PNG parser. The PNG standard does not require it to be handled for compliance, though I agree that it would be very useful to support it. I'll try to have a look and add that if I can find a moment. But if you want to have a go at fixing it feel free to do so.

**Comment by rlepigre** [comment]
I fixed the PNG part of the problem in ed848b27548cf7e0e39ec45c2e2dfe6256af6d38.

There also seems to be a problem with the GIF handling of transparency, but I am not familiar with the GIF format.
@cfcs can you have a look?

**Comment by cfcs** [comment]
As agreed in the GIF pr, but unfortunately not very clearly documented, the `ImageLib_unix` module falls back to a pass through `convert` (from `imagemagick`) and then uses our PNG code. This was done to prevent bugginess from the GIF module impacting existing users of ImageLib.

It is possible that we need to pass more flags to `convert` in `ImageLib_unix.convert` to preserve the alpha channel, if the code is not fixed by the recent PNG change?

To convert a file using the pure code (not the `_unix`) variant you can use the `imagetool` (may be called `imagetool.exe`, I'm not sure) that ships with ImageLib.

The syntax would be:
```shell
$ imagetool.exe turtle.gif turtle_conv.png
$ imagetool.exe turtle.gif turtle_conv.gif
```

**Comment by cfcs** [comment]
I tried it out - that didn't get us very far:
```shell
$ imagelib ./_build/default/app/imagetool.exe 100665162-75b70780-3358-11eb-9fc0-fb1bf816211a.gif turtle_conv.png
overwrite graphic with background color
overwrite graphic with background color
TODO NOT IMPLEMENTED: Writing image with >1 frames
```

I guess it would make sense to have a commandline flag to the utility to let it pick out a specific frame for the PNG conversion, and ... implementing the animated GIF writing.

**Comment by cfcs** [comment]
Building this commit
```
commit ed848b2 (HEAD -> master, origin/master)
Author: Rodolphe Lepigre <lepigre@mpi-sws.org>
Date:   Tue Dec 29 13:05:00 2020 +0100

    Add simple transparancy support to PNG (tRNS ancillary chunk).
```

Appears to have fixed the problem for PNG:
```shell
$ ./_build/default/app/imagetool.exe turtle-0.png  --character '  ' --background 0xff00ff
```

```shell
$ ./_build/default/app/imagetool.exe turtle-0.png turtle.conv.png
# turtle.conv.png: PNG image data, 96 x 96, 8-bit/color RGBA, non-interlaced
# the alpha channel is preserved
```

The pure GIF **writer** does not support transparency (`src/imageGIF.ml:write`), but it should be relatively simple to implement.

The pure GIF **reader** does support transparency, and this works for some GIFs, but not this one apparently. That is definitely a bug.
It is supposed to be handled in one of these two code blocks:

`src/imageGIF.ml:ReadGIF:process_image_descriptor_subblock`:
```ocaml
      write_rgba image x y
        (Char.code color_table.[offset  ])
        (Char.code color_table.[offset +1])
        (Char.code color_table.[offset +2])
        (if symbol = transparency_index then 0 else 0xff)
```

`src/imageGIF.ml:ReadGIF:read_streaming`:
```ocaml
            Image.read_rgba image x y
              (fun r g b -> function
                 | 0x00 -> begin match gif_state.buffer.pixels with
                     | RGBA (_,_,_,aa) -> Pixmap.set aa (left+x) (top+y) 0xff
                     | _ -> failwith "gif_state.buffer.pixels is not rgba"
                   end
                 | _ ->
                   Image.write_rgb gif_state.buffer (left+x) (top+y) r g b)
```


It could also be related to the setting of the transparency index (into the color palette):
```ocaml
            let transparency_index =
              (* transparent color index <- body.(3)
                 index into global color table.
                 TODO should this default to 0? *)
              match use_transparent_color with
              | true -> int_of_char body.[3]
              (* TODO maybe verify that the index fits the GCT? *)
              | false -> -1
            in
```

It would require closer inspection, but it looks like it might be the case that the transparency index is only handled correctly if the transparency index is set in the global color palette (see `read_streaming`) and the image doesn't use local color palettes. That could be the case with this GIF.

**Comment by cfcs** [comment]
OK, upon closer inspection the problem with `imagetool` and conversion from GIF appears to be that the scaling layer (for image resizing) which is currently a mandatory pass, even if no actual resizing takes place, blatantly ignores the alpha channel of an image. I will try to sort this out.

**Comment by cfcs** [comment]
> I fixed the PNG part of the problem in [ed848b2](https://github.com/rlepigre/ocaml-imagelib/commit/ed848b27548cf7e0e39ec45c2e2dfe6256af6d38).

By the way, it looks like you left debugging on:
https://github.com/rlepigre/ocaml-imagelib/blob/master/src/imagePNG.ml#L22

ping @rlepigre

**Comment by aryx** [comment]
Thx a lot @cfcs !

**Comment by rlepigre** [comment]
> By the way, it looks like you left debugging on:
> https://github.com/rlepigre/ocaml-imagelib/blob/master/src/imagePNG.ml#L22

Oups, sorry. Fixed in ddd29559dcd32d55a5bddfb47b9faefbfbbcadc3.

Thanks for looking into the problem @cfcs!

**Comment by cfcs** [comment]
OK, a bit deeper into the code now. Alpha channel was ignored for scaling. When not scaling, alpha for GIF is detected, but instead of returning an alpha-enabled image it fills the transparent spots out with the background color.
This is kind of unclearly specified for GIF, but I will try to see if I can make it mimick what browsers / other image viewers do in this case.

**Comment by cfcs** [comment]
I made a PR with my proposed changes. I'm pretty sure it's not correct for all cases (like with local color palettes and changing transparency/backgrounds), but at least it handles transparency better and solves @aryx' problem.

We're also still missing support for writing out animated GIFs, that will be left as an exercise for the reader for now. :-)

**Comment by cfcs** [comment]
@mseri would you be able to assist with cutting a release with these fixes?

**Comment by mseri** [comment]
Sure. I will do it later today or tomorrow

**Comment by mseri** [comment]
@cfcs release PR at https://github.com/ocaml/opam-repository/pull/17983
